[package]
name = "yeti"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
im = "15.1.0"
tokio = { version = "1.33.0", features = ["full"] }
compiler = { path = "./compiler" }
http = { path = "./http" }

[workspace]
members = [
  "compiler",
  "http"
]

