[package]
name = "toml"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
toml_lib = { version = "0.8.8", package = "toml" }
tokio = { version = "1.33.0", features = ["full"] }
compiler = { path = "../compiler" }

[lib]
path = "src/lib.rs"
