[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
im = "15.1.0"
compiler = { path = "../compiler" }

[lib]
path = "src/lib.rs"
