[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[features]
metal = ["candle-core/metal"]

[dependencies.candle-core]
git = "https://github.com/huggingface/candle.git"
branch = "metal4"
default-features = false

[lib]
path = "src/lib.rs"
