[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", branch = "metal4", features = ["metal"] }

[lib]
path = "src/lib.rs"
