[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
rug = "1.22.0"
tokio = { version = "1.33.0", features = ["full"] }
futures = "0.3.29"
compiler = { path = "../compiler" }

[lib]
path = "src/lib.rs"
