[package]
name = "yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
tokio = { version = "1.33.0", features = ["full"] }
serde_yaml = "0.9"
compiler = { path = "../compiler" }

[lib]
path = "src/lib.rs"
